feat: supabase から post を取得する処理
SystemEngineeringTeam/project-exercises-kuso pull request #25
Opened 2024-09-30 05:43 UTC by kanakanho

Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/8

## 説明

supabase から post を取得する処理を追加した

## 現在の動作 (更新前)

なし

## 新しい動作 (更新後)

supabase にアクセスして情報を取得して、`src/types/post.ts` の Post[] の型で渡します

2024-09-30 06:14 UTC, SatooRu65536 requested changes

2024-09-30 06:14 UTC, SatooRu65536 commented on src/stores/postAtom.ts
> +    resUsers.status !== 200 ||
ここら辺いらなさそう？
```suggestion
```

2024-09-30 06:14 UTC, SatooRu65536 commented on src/stores/postAtom.ts
> +      ) as PostTag[];
tag との紐付けは select でやってほしい
今は全ての post を取得しているが、今後改善するため
crazyScore も同様に

↓みたいな
```ts
resPosts.map((post) => {
  const resTag = await supabase.from('post_tag').select('post_id, tag').eq('post_id', post.id);
  // ...
})
```

2024-09-30 06:18 UTC, kanakanho commented on src/stores/postAtom.ts
> +    resUsers.status !== 200 ||
消した

2024-09-30 06:25 UTC, kanakanho commented on src/stores/postAtom.ts
> +      ) as PostTag[];
対応した

2024-10-01 03:26 UTC, SatooRu65536 requested changes

2024-10-01 03:26 UTC, SatooRu65536 commented on src/stores/postAtom.ts
> +  const resPosts = await supabase.from('post').select();
eq使えるって言ったけど、もっと簡潔にできた (ごめん)

```ts
  const resPosts = await supabase.from('post').select(`
    *,
    language (
      id,
      name
    ),
    user (
      uid
    ),
    post_tag (
      id,
      tag
    )
  `);
```

2024-10-01 03:26 UTC, SatooRu65536 commented on src/stores/postAtom.ts
> +        const averageCrazyScore =
https://supabase.com/blog/postgrest-aggregate-functions
select の時点で SQL の AVG 的なのがあるらしいけどよく分からんかった
できそうならやってみてほしい

2024-10-01 06:54 UTC, kanakanho commented on src/stores/postAtom.ts
> +  const resPosts = await supabase.from('post').select();
変更しました

2024-10-01 07:03 UTC, kanakanho commented on src/stores/postAtom.ts
> +        const averageCrazyScore =
やりません！！！

2024-10-01 07:17 UTC, merged

2024-10-01 07:17 UTC, SatooRu65536 commented
LGTM!